### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by zaneobrien** [rishabco/Gangopadhyay_CSCI2270_FinalProject#1]
It is not as much an issue as it is a suggestion. One thing you could add to the read me file is how to compile the program. something like this:

to compile:  g++ -std=c++11 Travel.cpp main.cpp 
to run: ./main

it would just add to the clarity of the readme file.

**Comment by rishabco** [comment]
Sure. Thanks for the feedback, I'll add that right away.

**Comment by rishabco** [comment]
Just a heads up zaneobrien our program now runs on terminal. See the updated readme file for details.

**Comment by zaneobrien** [comment]
looks great. Good job
