### ISSUE TITLE
Bug: Denver to Boston

### ISSUE THREAD

**Issue by JSD915** [rishabco/Gangopadhyay_CSCI2270_FinalProject#2]
Sorry I'm posting this bug so late, but when I try to travel from Denver to Boston the code crashes. Also travelling the other way says the total distance is 215 miles.

**Comment by JSD915** [comment]
Its not a actually a big deal. In the given cities.txt file, Boston should be -1,215,-1,-1,-1,-1,0,438,309,-1,-1,-1 where its currently -1,-1,215,-1,-1,-1,0,438,309,-1,-1,-1.

**Comment by kbhu** [comment]
Nice catch, uploaded the fixed .txt file.
